import type { Metadata } from "next";
import { Header } from "app/components/shared/Header";
import { Footer } from "app/components/shared/Footer";
import './styles/modern-normalize.css';
import './styles/style.css';
import './styles/utils.css';

import { Crimson_Text } from "next/font/google";
import { Montserrat } from "next/font/google";

const crimson_init = Crimson_Text({
  subsets: ['latin'],
  weight:['400', '600', '700'],
  variable: '--font-crimson',
});

const montserrat_init = Montserrat({
  subsets: ['latin'],
  weight:['400', '500', '600', '700'],
  variable: '--font-montserrat',
});


export const metadata: Metadata = {
  title: "Hotel Tacna Lodge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimson_init.variable} ${montserrat_init.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
